version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lockout
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@local.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - '5050:80'
networks:
  default:
    name: lockout
volumes:
  db:
    driver: local
