services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - neolockout-db:/var/lib/postgresql/data
    networks:
      - lockout

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - lockout

  bot:
    build: .
    container_name: bot
    restart: always
    depends_on:
      - db
    networks:
      - lockout
    links:
      - db:database

networks:
  lockout:
    driver: bridge

volumes:
  neolockout-db:
    driver: local
